- name: setup todo project
  hosts: all
  roles:
    - role: frontend
      tags: frontend
      when: COMPONENT == "frontend"

    - role: todo
      tags: users
      when: COMPONENT == "users"

    - role: todo
      tags: todo
      when: COMPONENT == "todo"



