
    - name: Install Nginx
      become: yes
      apt:
        name: nginx
        update_cache: yes
        state: present


    - name: start & enable nginx
      systemd:
        state: started
        name: nginx
        enabled: yes

    - name: Download artifact from nexus
      get_url:
        url: http://172.31.15.247:8081/repository/frontend/frontend-0.0.1.zip
        dest: /root/frontend
        username: admin
        password: admin123

    - name: extract the todo content
      unarchive:
        src: /root/frontend
        dest: /home/frontend/frontend
        remote_src: yes

    - name: install npm
      shell: sudo npm install

    - name: run npm build
      shell: npm run build

    - name: change root path in nginx
      replace:
        path: /etc/nginx/sites-available/default
        regexp: '/var/www/html'
        replace: '/var/www/html/todo/frontend/dist'

    - name: Replace ip with login ip
      replace:
          path: /var/www/html/todo/frontend/config/index.js
          regexp: '127.0.0.1'
          replace: '172.31.62.90'

    - name: Replace ip with todo ip
      replace:
          path: /var/www/html/todo/frontend/config/index.js
          regexp: '127.0.0.2'
          replace: '172.31.55.237'

    - name: start npm
      shell: npm start

    - name: restart nginx
      systemd:
        state: restarted
        name: nginx


