
    - name: Install Nginx
      become: yes
      apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Download artifact from nexus
      get_url:
        url: http://172.31.15.247:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp/frontend.zip
        username: admin
        password: admin123

    - name: Delete the default content
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx/sites-enabled/default
        - /etc/nginx/sites-available/default

    - name: creat a directory
      file:
        path: /home/frontend/frontend

    - name: extract the todo content
      unarchive:
        src: /tmp/frontend.zip
        dest: /home/frontend/frontend
        remote_src: yes

    - name: install npm
      shell: sudo npm install

    - name: run npm build
      shell: npm run build

    - name: change root path in nginx
      replace:
        path: /etc/nginx/sites-available/default
        regexp: '/var/www/html'
        replace: '/var/www/html/todo/frontend/dist'

    - name: Replace ip with login ip
      replace:
          path: /var/www/html/todo/frontend/config/index.js
          regexp: '127.0.0.1'
          replace: '172.31.62.90'

    - name: Replace ip with todo ip
      replace:
          path: /var/www/html/todo/frontend/config/index.js
          regexp: '127.0.0.2'
          replace: '172.31.55.237'

    - name: start npm
      shell: npm start

    - name: restart nginx
      systemd:
        state: restarted
        name: nginx
        enabled: yes


