- name: Install go
  become: yes
  apt:
    name: golang
    state: present
    update_cache: yes

- name: Download artifact from Nexus
  include_tasks: uploadartifacts.yml

- name: setup systemd service
  include_tasks: systemd.yml

- name: Install Node Exporter Prometheus Monitoring
  include_tasks: node_exporter

