- name: uninstall jdk 11
  become: yes
  apt:
    name: openjdk-11-jre-headless
    state: absent

- name: Update cache
  become: yes
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes

- name: install maven
  become: yes
  apt:
    name: maven
    state: present
    update_cache: yes